#!/bin/sh
set -eu

check_noreply_email() {
    identity_name="$1"
    identity_email="$2"
    case "$identity_email" in
        *@users.noreply.github.com|noreply@github.com)
            ;;
        *)
            echo "Commit blocked: $identity_name email must use a GitHub noreply address." >&2
            echo "Configure this repository with: git config user.email '<id>+<login>@users.noreply.github.com'" >&2
            exit 1
            ;;
    esac
}

author_email=$(git var GIT_AUTHOR_IDENT | sed -n 's/^[^<]*<\([^>]*\)>.*/\1/p')
committer_email=$(git var GIT_COMMITTER_IDENT | sed -n 's/^[^<]*<\([^>]*\)>.*/\1/p')
check_noreply_email "Author" "$author_email"
check_noreply_email "Committer" "$committer_email"
